config/routes.rb
Rails.application.routes.draw do
  # The landing page
  root 'welcome#index'
  # Opportunities endpoints
  resources :opportunities
  # Our Mission page
  resources :contacts, only: [:new, :create]
  get 'contacts/new'
  # Admin dashboard; only accessible for users with superadmin_role
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Devise routes
  devise_for :users
  # Donate button with stripe
  resources :charges
  # Search route
  resources :search, only: [:index]
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #7ed957;">
    <%= link_to image_tag("logo.png", size: "30x30", alt: "App Logo"), root_path %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item hvr-grow">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>

      <li class="nav-item hvr-grow">
        <%= link_to 'For Volunteers', opportunities_path, class: 'nav-link' %>
      </li>

      <li class="nav-item hvr-grow">
        <%= link_to 'For Organisations', new_opportunity_path, class: 'nav-link' %>
      </li>

      <li class="nav-item hvr-grow">
        <%= link_to 'Our Mission', contacts_new_path, class: 'nav-link' %>
      </li>

      <li class="nav-item hvr-grow">
        <%= link_to 'Donate', new_charge_path, class: 'nav-link' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item hvr-grow">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item hvr-grow">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item hvr-grow">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>

      <% if user_signed_in? && current_user.superadmin_role? %>
        <li class="nav-item hvr-grow">
          <%= link_to 'Admin', rails_admin.dashboard_path, class: 'nav-link' %>
        </li>
      <% end %>

      <% if user_signed_in? %>
        <li class="nav-item hvr-grow">
          <%= link_to 'Your Account', edit_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>