config/routes.rb
Rails.application.routes.draw do
  # The landing page
  root 'welcome#index'
  # Opportunities endpoints
  resources :opportunities
  # Our Mission page
  resources :contacts, only: [:new, :create]
  get 'contacts/new'
  # Admin dashboard; only accessible for users with superadmin_role
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # Devise routes
  devise_for :users
  # Donate button with stripe
  resources :charges
  # Search route
  resources :search, only: [:index]
end

app/models/opportunity.rb
class Opportunity < ApplicationRecord
  # validates and sanitises all input
    validates :organisation,
        presence: true,
        length: { minimum: 6 }

    validates :title,
        presence: true,
        length: { minimum: 6 }

    validates :location,
        presence: true,
        length: { minimum: 4 }

    validates :description,
        presence: true,
        length: { minimum: 10 }

    # One opportunity listing has zero or one image
    has_one_attached :image

    # An opportunity can only belong to one user
    belongs_to :user

    # Include pg_search gem
    include PgSearch::Model
    pg_search_scope :search, against: [:location, :title, :organisation]
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  # Anyone can view all the listings, but only authenticated or authorised users can access other controller actions
  skip_before_action :authenticate_user!, :only => [:index]

  # List all current volunteering opportunities
  def index
    if params[:query].present?
      @opportunities = Opportunity.search(params[:query])
    else
      @opportunities = Opportunity.all
    end
  end

  # Show one opportunity
  def show
    @opportunity = Opportunity.find(params[:id])
    @email = User.find(@opportunity.user_id).email
  end

  # Initialise a new opportunity listing
  def new
    @opportunity = Opportunity.new
  end

  # Render existing data in the edit form
  def edit
    @opportunity = Opportunity.find(params[:id])
  end

  # Associate a newly created opportunity listing to a particular user, only the user
  # that created the listing can edit or delete the listing
  def create
    @opportunity = current_user.opportunities.create(opportunity_params)
    
    Opportunity.new(opportunity_params)
   
    if @opportunity.save
      redirect_to @opportunity
    else
      render 'new'
    end
  end

  # Put/patch method to update a listing
  def update
    @opportunity = Opportunity.find(params[:id])
   
    if @opportunity.update(opportunity_params)
      redirect_to @opportunity
    else
      render 'edit'
    end
  end

  # Method to delete a listing
  def destroy
    @opportunity = Opportunity.find(params[:id])
    @opportunity.destroy
   
    redirect_to opportunities_path
  end

  private

  # Strong params
  def opportunity_params
    params.require(:opportunity).permit(:organisation, :title, :location, :description, :image)
  end
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/views/opportunities/edit.html.erb
<h1 class="text-center">Update opportunity</h1>

<%# Display any errors that are preventing the form from being saved %>
<% if @opportunity.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@opportunity.errors.count, "error") %> prohibited
        this opportunity from being saved:
      </h2>
      <ul>
        <% @opportunity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%# Edit form with existing data %>
<div id="container" class="container">
  <div class="row">
    <div class="col-sm-10 offset-sm-1 text-center">
      <div class="info-form">
        <%= form_with(model: @opportunity, local: true) do |form| %>
          <p>
            <%= form.label :organisation %><br>
            <%= form.text_field :organisation %>
          </p>

        <p>
            <%= form.label :title %><br>
            <%= form.text_field :title %>
        </p>

        <p>
            <%= form.label :location %><br>
            <%= form.text_field :location %>
        </p>
        
          <p>
            <%= form.label :description %><br>
            <%= form.text_area :description %>
          </p>
        
          <p>
            <%= form.submit "Update"%>
          </p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%# Hyperlink to go back to the index page %>
<div class="d-flex justify-content-center">
  <button type="button" class="btn btn-outline-info"><%= link_to 'Back', opportunities_path %></button>
</div>

app/views/opportunities/index.html.erb
<h1 class="text-center">Current Opportunities</h1>

<%# Search form %>
<div id="container" class="container">
  <div class="row">
    <div class="col-sm-10 offset-sm-1 text-center">
      <div class="info-form">
        <%= form_tag(opportunities_path, method: "get") do %>
          <%= text_field_tag 'query', nil, placeholder: 'Enter keyword...' %>
          <%= submit_tag "Search" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<br>

<%# Opportunities index page displaying all current opportunities %>
<div class="container"> 
  <div class="card-deck"> 
  <% @opportunities.each do |opportunity| %> 
      
      <div class="card text-white bg-success mb-3" style="min-width: 18rem;">
        <div class="card-body">
            <h5 class="card-title"><%=opportunity.title%></h5>
            <p class="card-text mt-2"><%=opportunity.organisation %></p>
            <p class="card-text"><small class=""><%= opportunity.location %></small></p>
            <button type="button" class="btn btn-warning"><p class="card-text text-center"><%= link_to 'More details', opportunity_path(opportunity) %></p></button>
        </div>
      </div> 
  <%end%> 
  </div> 
</div>

app/views/opportunities/new.html.erb
<p class="text-center">This page is only accessible to approved organisations!</p>
<p class="text-center">Please click <%= link_to 'here', new_contact_path %> to contact us for approval</p>

<%# Display any errors that are preventing the form from being saved %>
<% if @opportunity.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@opportunity.errors.count, "error") %> prohibited
        this opportunity from being saved:
      </h2>
      <ul>
        <% @opportunity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%# Only users with admin or organisation role can create a new opportunity %>
<div id="container" class="container">
  <div class="row">
    <div class="col-sm-10 offset-sm-1 text-center">
      <div class="info-form">
        <% if current_user.superadmin_role? || current_user.organisation_role? %>

        <h1 class="text-center">Create New Listing</h1>

        <%= form_with scope: :opportunity, url: opportunities_path, local: true do |form| %>
          <p>
            <%= form.label :organisation %><br>
            <%= form.text_field :organisation %>
          </p>

          <p>
              <%= form.label :title %><br>
              <%= form.text_field :title %>
          </p>

          <p>
              <%= form.label :location %><br>
              <%= form.text_field :location %>
          </p>
        
          <p>
            <%= form.label :description %><br>
            <%= form.text_area :description %>
          </p>
        
          <p>
            <%= form.label :image %><br>
            <%= form.file_field :image, accept: 'image/png, image/jpg, image/jpeg' %>
          </p>

          <p>
            <%= form.submit "Create New Opportunity"%>
          </p>
        <% end %>

        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center">
  <button type="button" class="btn btn-outline-info"><%= link_to 'Back', opportunities_path %></button>
</div>

app/views/opportunities/show.html.erb
<br>
<div class="card mb-3 mx-auto bg-warning" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <% if @opportunity.image.attached? %>
        <%= image_tag @opportunity.image, :class => "img-fluid w-75 rounded mx-auto d-block" %>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= @opportunity.title %> @ <%= @opportunity.organisation %></h5>
        <p class="card-text"><%= @opportunity.location %></p>
        <p class="card-text"><%= @opportunity.description %></p>
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center">
  <button type="button" class="btn btn-outline-success"><%= mail_to @email, "I'm interested in this opportunity", subject: "Volunteer Opportunity" %></button>
</div>

<br>

<div class="text-center">
  <% if current_user %>
    <% if current_user.id == @opportunity.user_id || current_user.superadmin_role? %>
      <button type="button" class="btn btn-outline-info"><%= link_to 'Edit', edit_opportunity_path(@opportunity) %></button>
      <button type="button" class="btn btn-outline-info"><%= link_to 'Delete', opportunity_path(@opportunity),
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %></button>
    <% end %>
  <% end %>

  <button type="button" class="btn btn-outline-info"><%= link_to 'Back', opportunities_path %></button>
</div>